version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: cars-mania-backend-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL:-file:/app/prisma/dev.db}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-dev_access_secret}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-dev_refresh_secret}
      - ACCESS_TOKEN_TTL_SECONDS=${ACCESS_TOKEN_TTL_SECONDS:-900}
      - REFRESH_TOKEN_TTL_SECONDS=${REFRESH_TOKEN_TTL_SECONDS:-1209600}
      - PORT=3001
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cars-mania-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cars-mania-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - .env.development
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:3001}
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cars-mania-network

networks:
  cars-mania-network:
    driver: bridge
