version: '3.8'

services:
  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/petarnenov/cars-mania/backend:latest}
    container_name: cars-mania-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_TOKEN_TTL_SECONDS=${ACCESS_TOKEN_TTL_SECONDS:-900}
      - REFRESH_TOKEN_TTL_SECONDS=${REFRESH_TOKEN_TTL_SECONDS:-1209600}
      - PORT=3001
    volumes:
      - ./uploads:/app/uploads
      - ./prisma:/app/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cars-mania-network

  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/petarnenov/cars-mania/frontend:latest}
    container_name: cars-mania-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env.production
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:3001}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cars-mania-network

  # Optional: Add a reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    container_name: cars-mania-nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - cars-mania-network
    profiles:
      - ssl

networks:
  cars-mania-network:
    driver: bridge
