name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Prepare backend test DB (Prisma push)
        working-directory: backend
        env:
          NODE_ENV: test
          DATABASE_URL: file:./unit-test.db
        run: npx prisma db push --skip-generate --schema=prisma/schema.prisma

      - name: Type-check backend
        working-directory: backend
        run: npm run build

      - name: Lint backend
        working-directory: backend
        run: npm run lint

      - name: Backend tests
        working-directory: backend
        env:
          JWT_ACCESS_SECRET: test_access_secret
          JWT_REFRESH_SECRET: test_refresh_secret
          ACCESS_TOKEN_TTL_SECONDS: 900
          REFRESH_TOKEN_TTL_SECONDS: 1209600
          DATABASE_URL: file:./unit-test.db
        run: npm run test:cov

      - name: Upload backend coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage
          if-no-files-found: ignore

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Unit tests (frontend)
        working-directory: frontend
        run: npm run test:run

      - name: Coverage (frontend)
        working-directory: frontend
        run: npm run test:cov

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
          if-no-files-found: ignore

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: E2E tests (frontend)
        working-directory: frontend
        env:
          HEADLESS: "true"
        run: npm run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          if-no-files-found: ignore

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest

      - name: Docker Compose up (smoke and e2e)
        run: |
          export BACKEND_IMAGE=ghcr.io/${{ github.repository }}/backend:latest
          export FRONTEND_IMAGE=ghcr.io/${{ github.repository }}/frontend:latest
          docker compose -f docker-compose.ci.yml up -d
          # wait for services
          up=0
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:3001/health >/dev/null; then echo backend up; up=1; break; fi; sleep 1; done
          if [ "$up" != "1" ]; then echo "backend did not become ready"; docker compose -f docker-compose.ci.yml logs backend || true; exit 1; fi
          # run playwright against dockerized site
          cd frontend
          npm ci
          npx playwright install --with-deps
          E2E_BASE_URL=http://localhost:5173 BACKEND_URL=http://127.0.0.1:3001 npm run e2e
          cd ..
          docker compose logs backend | tail -n 200 || true
        env:
          JWT_ACCESS_SECRET: test_access_secret
          JWT_REFRESH_SECRET: test_refresh_secret
          BACKEND_IMAGE: ghcr.io/${{ github.repository }}/backend:latest
          FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/frontend:latest
